### ISSUE TITLE
Eventuele naamsverandering

### ISSUE THREAD

**Issue by tim-vandenbosch** [davidcyp/PXL#1]
# Aanpassing van repo
## reden

Sinds we bezig zijn aan het project van Appdev en nog een extra project krijgen van Basic security,
zou het mogelijk kunnen zijn om de naam van de repo te veranderen naar een lichter passende naam
## voorstel

Is het mogelijk om de naam `PXL JAVA ADVANCED` te gebruiken?
Dit is slechts een voorstel.

MvG
Tim Van Den Bosch
2Tini

**Comment by davidcyp** [comment]
Tim,

Als dit verwarring brengt wil ik dit gerust veranderen. Maar volstaat het niet om je repository name die je er aan toekent in bvb SourceTree te veranderen, om verwarring te voorkomen? Of treden er nog andere problemen op?
